### ISSUE TITLE
Max length on main mapcode pieces?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/mapcode-regex#1]
I need to figure out if there's a max length on the main mapcode pieces.

Example: `ZSR` and `3J` in `Hawaii ZSR.3J`.

From looking at a bunch of codes I would guess it's minimum 2 and maximum 5. But can't be sure until I see some documentation on it.

**Comment by kevva** [comment]
http://www.mapcode.com/mapcode_documentation.doc. Couldn't find anything about the max length of the pieces though.

**Comment by sindresorhus** [comment]
Yeah, I've previously read through that, but didn't find anything either. I've tried emailing them. Let's see if we can get an answer.

**Comment by sindresorhus** [comment]
Alright, got a reply with what's needed an more. Looks like there are more things we can implement to make it even stricter: https://dl.dropboxusercontent.com/u/71884/Length%20and%20format%20of%20mapcodes.pdf
