### ISSUE TITLE
Make regex stricter

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/mapcode-regex#3]
Continuation of #1.

> Alright, got a reply with what's needed an more. Looks like there are more things we can implement to make it even stricter: https://dl.dropboxusercontent.com/u/71884/Length%20and%20format%20of%20mapcodes.pdf

**Comment by rijnb** [comment]
Hi, for a full spec of the mapcode format, have a look at the renewed documentation on http://mapcode.com.
It seems the current regex does not fully comply with the latest list of countries/states and the mapcode part itself is better written as:
[ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjklmnpqrstuvwxyz0-9]{2,}[.][ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjklmnpqrstuvwxyz0-9]{2,}([-][0-9]{1,8})?

Vowels are never used, except AEU for some languages (very few) and high precision mapcodes are specified as XX.XX-123 (with 1-8 digits).

Have fun and happy coding!
Rijn Buve (Mapcode Foundation)
